[book]
title = "凹语言手册"
authors = ["凹语言开发组"]
description = "凹语言手册"
src = "."
language = "en"

[output.html]
git-repository-url = "https://github.com/wa-lang/man"
edit-url-template = "https://github.com/wa-lang/man/edit/master/{path}"
git-repository-icon = "fa-github"
